college_map = {
    "aelts.khu.ac.kr": "응용통번역학과",
    "afd.khu.ac.kr": "아트퓨전디자인대학원",
    "and.khu.ac.kr": "예술디자인대학",
    "applsci.khu.ac.kr": "응용과학대학",
    "biology.khu.ac.kr": "생물학과",
    "bme.khu.ac.kr": "생체의공학과",
    "ce.khu.ac.kr": "컴퓨터공학과",
    "che.khu.ac.kr": "생활과학대학",
    "chem.khu.ac.kr": "화학과",
    "cominv.khu.ac.kr": "국제통상 금융투자학부",
    "communication.khu.ac.kr": "미디어커뮤니케이션대학원",
    "coop.khu.ac.kr": "경희대학교 생활협동조합",
    "dance.khu.ac.kr": "무용학부",
    "dental.khu.ac.kr": "치과대학 치의학전문대학원",
    "deptofenglish.khu.ac.kr": "글로벌커뮤니케이션학부",
    "display.khu.ac.kr": "정보디스플레이학과",
    "dorm2.khu.ac.kr": "제2기숙사",
    "econ.khu.ac.kr": "경제학과",
    "edu.khu.ac.kr": "교육대학원",
    "education.khu.ac.kr": "교무처 교직팀",
    "ee.khu.ac.kr": "전자공학과",
    "eng.khu.ac.kr": "공과대학",
    "eni.khu.ac.kr": "전자정보대학",
    "foreign.khu.ac.kr": "외국어대학",
    "france.khu.ac.kr": "프랑스어학과",
    "geo.khu.ac.kr": "지리학과",
    "goodjob.khu.ac.kr": "미래인재센터",
    "gradsport.khu.ac.kr": "체육대학원",
    "gskh.khu.ac.kr": "경희대학교 대학원",
    "gsm.khu.ac.kr": "동서의학대학원",
    "gsp.khu.ac.kr": "국제대학원",
    "gukmun.khu.ac.kr": "국어국문학과",
    "happydorm.khu.ac.kr": "행복기숙사",
    "hc.khu.ac.kr": "후마니타스 칼리지",
    "history.khu.ac.kr": "사학과",
    "hot.khu.ac.kr": "호텔관광대학",
    "human.khu.ac.kr": "문과대학",
    "iie.khu.ac.kr": "국제교육원",
    "janghak.khu.ac.kr": "학생지원센터(장학)",
    "japanese.khu.ac.kr": "일본어학과",
    "kbiz.khu.ac.kr": "경영대학",
    "khcns21.khu.ac.kr": "간호과학대학",
    "khenglish.khu.ac.kr": "영어영문학과",
    "khmba.khu.ac.kr": "영어영문학과",
    "khsma.khu.ac.kr": "정경대학",
    "khuart.khu.ac.kr": "미술대학",
    "khusm.khu.ac.kr": "의과대학",
    "kic.khu.ac.kr": "국제대학",
    "kmc.khu.ac.kr": "한의과대학",
    "korean.khu.ac.kr": "한국어학과",
    "law.khu.ac.kr": "법무대학원",
    "library.khu.ac.kr": "중앙도서관",
    "maths.khu.ac.kr": "수학과",
    "media.khu.ac.kr": "MEDIA CENTER",
    "mediacom.khu.ac.kr": "미디어학과",
    "museum.khu.ac.kr": "중앙박물관",
    "music.khu.ac.kr": "음악대학",
    "pa.khu.ac.kr": "행정학과",
    "pharm.khu.ac.kr": "약학대학",
    "phy.khu.ac.kr": "물리학과",
    "physics.khu.ac.kr": "응용물리학과",
    "pnc.khu.ac.kr": "공공대학원",
    "politics.khu.ac.kr": "정치외교학과",
    "russia.khu.ac.kr": "러시아어학과",
    "science.khu.ac.kr": "이과대학",
    "sewhahall.khu.ac.kr": "세화원 기숙사",
    "smartfarmsci.khu.ac.kr": "스마트팜과학과",
    "soc.khu.ac.kr": "사회학과",
    "software.khu.ac.kr": "소프트웨어융합대학",
    "sophia.khu.ac.kr": "문과대학 철학과",
    "space.khu.ac.kr": "우주과학과",
    "spanish.khu.ac.kr": "스페인어학과",
    "sports.khu.ac.kr": "체육대학",
    "swcon.khu.ac.kr": "소프트웨어융합대학",
    "swedu.khu.ac.kr": "SW중심사업단",
    "trade.khu.ac.kr": "무역학과",
    "wjwdorm.khu.ac.kr": "우정원 기숙사",
    "www.khu.ac.kr": "경희대학교",
    "zhongwen.khu.ac.kr": "중국어학과",
}
